apiVersion: v1
kind: Service
metadata:
  name: streamnest-frontend
  namespace: streamnest-frontend

spec:
  selector:
    app: streamnest-frontend

  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

  type: NodePort
